
# Various rules that can be or'ed together
VRPH_DOWNHILL = 1
VRPH_RECORD_TO_RECORD = 1<<1
VRPH_SIMULATED_ANNEALING = 1<<2
VRPH_FIRST_ACCEPT = 1<<3
VRPH_BEST_ACCEPT = 1<<4
VRPH_LI_ACCEPT = 1<<5
VRPH_INTER_ROUTE_ONLY = 1<<6
VRPH_INTRA_ROUTE_ONLY = 1<<7
VRPH_USE_NEIGHBOR_LIST = 1<<8
VRPH_FREE = 1<<9
VRPH_BALANCED = 1<<10
VRPH_FORWARD = 1<<11
VRPH_BACKWARD = 1<<12
VRPH_RANDOMIZED = 1<<13
VRPH_SAVINGS_ONLY  = 1<<14
VRPH_MINIMIZE_NUM_ROUTES = 1<<15
VRPH_FIXED_EDGES = 1<<17
VRPH_ALLOW_INFEASIBLE = 1<<18
VRPH_NO_NEW_ROUTE = 1<<19
VRPH_TABU = 1<<20


# Heuristic operations
ONE_POINT_MOVE = 1<<21
TWO_POINT_MOVE = 1<<22
TWO_OPT = 1<<23
OR_OPT = 1<<24
THREE_OPT = 1<<25
CROSS_EXCHANGE = 1<<26
THREE_POINT_MOVE = 1<<27
KITCHEN_SINK = 1<<28

#ALL_HEURISTICS====  (1<<20)|(1<<21)|(1<<22)|(1<<23)|(1<<24)|(1<<25)|(1<<26)|(1<<27)

#cutom rules



# Values of heuristics that can be used in functions such as 
# clean_routes

NUM_HEURISTICS = 7

ONE_POINT_MOVE_INDEX = 0  
TWO_POINT_MOVE_INDEX  = 1
TWO_OPT_INDEX = 2
OR_OPT_INDEX = 3
THREE_OPT_INDEX = 4
CROSS_EXCHANGE_INDEX = 5
THREE_POINT_MOVE_INDEX = 6



# Move types
PRESERT = 1
POSTSERT = 2
CONCATENATE = 3
SWAP_ENDS = 4
FLIP = 5
MOVE_STRING = 6
SWAP = 7

#endif


# Supported TSPLIB Problem types
VRPH_TSP = 1
VRPH_CVRP = 2

# Supported TSPLIB Edge Weight Formats
VRPH_FUNCTION = 1
VRPH_UPPER_ROW = 2
VRPH_FULL_MATRIX = 3
VRPH_LOWER_ROW = 4
VRPH_UPPER_DIAG_ROW = 5
VRPH_LOWER_DIAG_ROW = 6

# Supported TSPLIB Coord types
VRPH_TWOD_COORDS = 2
VRPH_THREED_COORDS = 3

# Supported TSPLIB Edge Weight Types
VRPH_EXPLICIT = 0
VRPH_EUC_2D = 1
VRPH_EUC_3D = 2
VRPH_MAX_2D = 3
VRPH_MAX_3D = 4
VRPH_MAN_2D = 5
VRPH_MAN_3D = 6
VRPH_CEIL_2D =7
VRPH_GEO = 8
VRPH_EXACT_2D = 9